apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sealed-secrets-operatorgroup
  namespace: sealed-secrets
spec:
  targetNamespaces:
    - sealed-secrets
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/sealed-secrets-operator-helm.sealed-secrets: ''
  name: sealed-secrets-operator-helm
  namespace: sealed-secrets
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: sealed-secrets-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace