apiVersion: bitnami.com/v1alpha1
kind: SealedSecretController
metadata:
  name: sealedsecretcontroller
  namespace: sealed-secrets
spec:
  networkPolicy: false
  nodeSelector: {}
  podLabels: {}
  resources: {}
  affinity: {}
  securityContext:
    runAsUser: ''
    fsGroup: ''
  rbac:
    create: true
    pspEnabled: false
  crd:
    create: true
    keep: true
  ingress:
    enabled: false
    annotations: {}
    path: /v1/cert.pem
    hosts:
      - chart-example.local
    tls: []
  serviceAccount:
    create: true
    name: ''
  image:
    repository: >-
      quay.io/bitnami/sealed-secrets-controller@sha256:8e9a37bb2e1a6f3a8bee949e3af0e9dab0d7dca618f1a63048dc541b5d554985
    pullPolicy: IfNotPresent
  secretName: sealed-secrets-key
  tolerations: []
  controller:
    create: true
  priorityClassName: ''
  podAnnotations: {}
