apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCJrzkU4EJf5H3LYiyNr7nG0yXA4ROsnKLcHtGO7T1f71WmeIvUNxwO8I6NphoTzDu8CAlnwfi/B+58sRyoWJts4NO2xgwGwcyKqtkV5iLNKIEvzxLEPcQuD3rKgeEXxWeDSxvCREty6u/iB62pKS8n+mmqlgugQZQCwOCOAeEjV3l+fCXaL2xYcxSzoQkQtwAKmSC0xvMI5W9bz42S28FdZXpKmZjNC+oryfAGx4ZdGihOCb+X0cnO8WocoYU5U+2jtNxCY9XlJKOtdO0QBB6HXosnSPrOHt68tkwvxdztqGp2vXPbD4hUCX4NhxMropINz9bYpUsmy9m/E0Kz38K1bHyBCo1TrkzwyZ4KNRM8qs0Z/Wwc3MFD4uPTmH/R8PMNZTK4xO03s1jzF07mCwcTjNofsOWRhkkF1rexlqRb5jXrMnR1otv8/aOiPuxYbvM4msEmIqiz36+lCqqvFeRHBpO+bBu+hE1TB32VlKT6OCXE1XrhvS61Z7C2VtxWtRAKXUtNGvXaFaLbcy/gdGAWnNM3nRrpwFLYFQh5E3/NQ1vASVbWSFPM1tC80zAQEYyL4hbYNE19N1Bvjj/OCK+S54D0q0U3gTU5b6F40MjaJ7zGbCpLlkbLaO98PKvlG6wJRHXQ0mS8k7JO0kT3Zy046X4aT9aV1EGwZ4VA9iM24O/WjIIxXw3q7z92ufEi5ABUVs6mH04byDG+
    user: AgB2yMYOPd0uDSHi52Q+WZpDBM+CYN2enw8yeE7yHVtErIgMLtthNCPINRlmikY16NByoOhzzumKTHfPgfUQMcicUr2alrmrBiq5K8gOm7yMmgC1T1b+IfMmEnQrds2OMEDRawSK3r5S54vD6koCYYJFKlgWTZBeDKcL2azN2PkjNQuXXJTfSKunVNQqmYkzigYyQ2fZtZi8za/yvZFy6IVVXThn1VWUZa5AeZwj9lExPGScSywX/q3g+dSMc4BUb772r7tFR6KMfaEvIRafVvJZBOfTzFOEVXOM9SNCqJzgMQnifKWCw9yioosz0HFadZ5aGbLM61LTATC7mFHwzYyoSueHNJxj7upp39NyvlcLZSPqPBn6G3Z6fHALefa0Im+4C0DjHO0u2Vy6yH5FTshmspU7cYsPta9aBj+eSU5CE8vMLnry7LoMwwap8oCOYOo0USOupnEuEwNVuUnrq4d507i55uaN30sqi5bP0hEvsmJtD0w28LgnMHxfG2yryw6vhBDees77zo+5xW8EvbKBEwKytVohlC08OT+KKOWSTvP5Fz0wT0wwCoVXho+FIQH/FM7x/LYgSFz1N9TBHejBsSa56uG3xruvwG5EadkeyYNpYnZ5CMzTAovvF6vGm/jkRn7bNi+YyB9jMxgpx5rgENYtMAZcZNK2iYC3B8AkwfI6eyEiS0ZcSTsU92QWQ19Z6lGpEo5YDA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

